---

- hosts: ProdUILB
  remote_user: bitnami
  serial: 2
  pre_tasks:
    - name: Gathering ec2 facts
      action: ec2_facts
    - name: De-register Instance from ELB to restart apache post SSL copy
      local_action:
        module: ec2_elb
        profile: "{{ aws_profile }}"
        instance_id: "{{ ansible_ec2_instance_id }}"
        aws_region: "{{ aws_region }}"
        state: absent

  roles:
    - copyssl
    - restart

  post_tasks:
  - name: Registering instance back to ELB
    local_action:
      module: ec2_elb
      profile: "{{ aws_profile }}"
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "{{ item }}"
      aws_region: "{{ aws_region }}"
      state: present
      wait: yes
      wait_timeout: 180
    with_items: "{{ ec2_elbs }}"

- name: Update MySQL Record
  hosts: localhost
  roles:
    - updatedb
