---
- hosts: all
  user: "{{ user }}"
  serial: 50
  roles:
    #- common
    - git_c
    - install
    - restart

  tasks:
   - name: Post Deployment update status @lead.birdeye.com post
     shell: wget -qO- "http://lead.birdeye.com/aggregation/updateserver?env=prod&ip="{{ ansible_host }}"&update_status=1&remark=Updated Successfully" &> /dev/null;
