---
- name: Stop bam node instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
    region: us-east-1
  tasks:
    - name: Stop the bam node instances
      local_action:
        module: ec2
        instance_ids: '{{ instance_ids }}'
        region: us-east-1
        state: stopped
        wait: True

- name: Start bam node instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
    region: us-east-1
  tasks:
    - name: Start the bam node instances
      local_action:
        module: ec2
        instance_ids: '{{ instance_ids }}'
        region: us-east-1
        state: running
        wait: True
